# Generated by Django 4.2.4 on 2024-05-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=20)),
                ('project_topic', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CommitMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_message', models.CharField(max_length=1024)),
                ('rate', models.IntegerField(null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
        ),
    ]
