# Generated by Django 4.2.4 on 2024-05-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmessage',
            name='scenario',
        ),
    ]
