# Generated by Django 4.2.4 on 2024-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commitmessage_scenario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitmessage',
            old_name='scenario',
            new_name='key',
        ),
    ]
