# Generated by Django 4.2.4 on 2024-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_scenario_commitmessage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmessage',
            name='rate',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
